### ISSUE TITLE
opening the portal in the "level1" scene raises an UnityException: Transform child out of bounds

### ISSUE THREAD

**Issue by RoW171** [RoW171/EIGE-Project#2]
**Error message**
UnityException: Transform child out of bounds
PortalSkript.Update () (at Assets/Scripts/LevelUtils/PortalSkript.cs:12)

**reproduce**
1. play level1
2. collect orb on the way
3. place orb at the pedestal at the end
4. error occurs , no portal appears

**Expected behavior**
- no exception, portal appears

**Desktop:**
 - OS: Windows[Version	10.0.18362 Build 18362]
- UNITY: 2019.2.17f1 [DX11]

**Comment by Simolater** [comment]
Known error. Fixed with PortalPedestal. Needs to be replaced with default pedestal and reference of portal set to the pedestal
